name: CD

on:
  release:
    types:
      - created

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  publish:
    name: Publish

    runs-on: ubuntu-latest

    needs:
      - ci

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Get version from git tag
        uses: battila7/get-version-action@v2
        id: get_version

      - name: Set version in package.json
        run: npm --no-git-tag-version version ${{ steps.get_version.outputs.version-without-v }}

      - name: Install dependencies
        run: npm ci

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: ./dist

      - name: Get publish tag
        uses: tobysmith568/npm-publish-latest-tag@v1
        id: latest_tag
        with:
          package-json: ./package.json

      - name: Publish to npm
        run: npm publish --access public --tag ${{ steps.latest_tag.outputs.latest-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
