name: npm Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - id: get_version
        uses: battila7/get-version-action@v2

      - run: npm --no-git-tag-version version ${{ steps.get_version.outputs.version-without-v }}
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
